import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';
import { browserLaunchOptions } from './browser.mjs';

const browser = await chromium.launch({ ...browserLaunchOptions(), headless: true });
try {
  const page = await browser.newPage();
  let scans = 0;
  const employee = { id: 'session-check', nip: '199001012020011001', name: 'Pengguna uji lokal', position: 'Pelaksana', satker: 'Satker uji', department: 'umum_keuangan', supervisor: { nip: '198001012010011001', name: 'Atasan uji' } };
  let sessionEmployee = employee;
  await page.route('**/api/session', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ employee: sessionEmployee, pending: null }) }));
  await page.route('**/api/session/end', route => { sessionEmployee = null; return route.fulfill({ contentType: 'application/json', body: '{}' }); });
  await page.route('**/api/employees/session-check/personal-template', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ activities: [], personal: null }) }));
  await page.route('**/api/verification/preview?*', route => { scans++; return route.fulfill({ contentType: 'application/json', body: JSON.stringify({ stageToken: 'local-test', targets: [{hllk:'test',date:'2026-09-01',valid:true}] }) }); });
  await page.goto('http://127.0.0.1:4545/');
  await page.waitForFunction(() => document.querySelector('#calendarGrid button'));
  await page.locator('#workChoices').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#workChoices').isVisible(), true);
  assert.equal(await page.locator('#createLlkMode').isVisible(), true);
  assert.equal(scans, 0);
  const result = await page.evaluate(() => {
    updateCalendarSelection('2026-08-31', '2026-09-04');
    const calendar = document.querySelector('#calendarSummary').textContent;
    document.querySelector('[name="workflowMode"][value="verify"]').checked = true;
    setWizardStep(2);
    const verify = { title: document.querySelector('#workTitle').textContent, reviewHidden: !document.querySelector('#reviewStep').classList.contains('is-active') };
    document.querySelector('[name="workflowMode"][value="create"]').checked = true;
    renderPreview(['2026-09-01', '2026-09-02'].map(date => ({ date, items: [{ start: '08:00', end: '16:30', description: 'Pemeriksaan UI lokal', type: 'Utama', result: 'Selesai' }] })));
    setWizardStep(3);
    const collapsed = document.querySelectorAll('.day-details:not([open])').length;
    document.querySelector('[data-toggle-edit="0"]').click();
    const field = document.querySelector('[data-field="description"]');
    field.value = 'Isian diperbarui';
    field.dispatchEvent(new Event('input', { bubbles: true }));
    const edited = currentPreview[0].items[0].description;
    const sendDisabled = document.querySelector('#submitBtn').disabled;
    const results = document.createElement('div');
    results.innerHTML = verificationList([{ date: '2026-09-01', success: true }, { date: '2026-09-02', success: false, error: 'net::ERR_ABORTED' }], 'result');
    return { calendar, verify, collapsed, edited, sendDisabled, firstResult: results.querySelector('strong').textContent, details: results.querySelectorAll('.error-details').length };
  });
  assert.match(result.calendar, /^5 hari kerja dipilih · 0 hari dilewati/);
  assert.deepEqual(result.verify, { title: 'Verifikasi LLK Anggota', reviewHidden: true });
  assert.equal(result.collapsed, 2);
  assert.equal(result.edited, 'Isian diperbarui');
  assert.equal(result.sendDisabled, true);
  assert.equal(result.firstResult, '2026-09-02');
  assert.equal(result.details, 1);
  await page.locator('[name="workflowMode"][value="verify"]').check();
  assert.equal(scans, 0);
  await page.locator('#refreshWizardVerificationBtn').click();
  await page.waitForFunction(() => !document.body.classList.contains('is-busy'));
  await page.locator('#wizardVerificationMessage').fill('Pesan tetap tersimpan');
  await page.locator('[name="workflowMode"][value="create"]').check();
  assert.equal(await page.locator('#reviewStep').isVisible(), true);
  assert.equal(await page.locator('[data-field="description"]').first().inputValue(), 'Isian diperbarui');
  await page.locator('[name="workflowMode"][value="verify"]').check();
  assert.equal(await page.locator('#wizardVerificationMessage').inputValue(), 'Pesan tetap tersimpan');
  assert.equal(scans, 1);
  assert.equal(await page.locator('#logBox').isVisible(), true);
  const logState = await page.evaluate(() => {
    log('Urutan awal', 'Berjalan'); log('Urutan akhir token=RAHASIA', 'Selesai');
    const box = document.querySelector('#logBox'), text = box.textContent;
    for (let i = 0; i < 60; i++) log(`Proses ${i}`);
    const following = box.scrollHeight - box.scrollTop - box.clientHeight < 24;
    box.scrollTop = 0; log('Tidak merebut posisi baca');
    return { ordered: text.indexOf('Urutan awal') < text.indexOf('Urutan akhir'), safe: !text.includes('RAHASIA'), following, retained: box.scrollTop === 0 };
  });
  assert.deepEqual(logState, { ordered: true, safe: true, following: true, retained: true });
  await page.reload();
  await page.locator('#workChoices').waitFor({ state: 'visible' });
  page.on('dialog', dialog => dialog.accept());
  await page.locator('#endSessionBtn').click();
  await page.locator('#quickSsoLoginBtn').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#workspace').isVisible(), false);
  assert.equal(await page.locator('#quickSupervisorNip').inputValue(), '');
  await page.reload();
  await page.locator('#quickSsoLoginBtn').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#workChoices').isVisible(), false);
  console.log('PASS: workflow, cross-month calendar, preview editing, required confirmation, and failure details. No production submissions.');
} finally { await browser.close(); }
