import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';
import { browserLaunchOptions } from './browser.mjs';

const browser = await chromium.launch({ ...browserLaunchOptions(), headless: true });
try {
  const page = await browser.newPage();
  await page.clock.setFixedTime(new Date('2026-10-06T10:00:00+07:00'));
  await page.route('**/api/**', route => {
    if (route.request().method() !== 'GET') throw new Error(`Mutasi tanpa fixture: ${route.request().url()}`);
    return route.continue();
  });
  let scans = 0;
  const employee = { id: 'session-check', nip: '199001012020011001', name: 'Pengguna uji lokal', position: 'Pelaksana', satker: 'Satker uji', department: 'umum_keuangan', supervisor: { nip: '198001012010011001', name: 'Atasan uji' } };
  let sessionEmployee = employee;
  await page.route('**/api/session', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ employee: sessionEmployee, pending: null }) }));
  await page.route('**/api/session/end', route => { sessionEmployee = null; return route.fulfill({ contentType: 'application/json', body: '{}' }); });
  await page.route('**/api/progress?*', route => route.fulfill({ json: { sequence: 0, events: [], active: false, latest: null } }));
  await page.route('**/api/employees/session-check/personal-template', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ activities: [], personal: null }) }));
  await page.route('**/api/employees/session-check/calendar-entries*', route => route.fulfill({ json: { dates: ['2026-09-14', '2026-09-16'], scope: 'all-pages', complete:true, pagesScanned:2, available: true, fetchedAt: '2026-09-18T06:00:00Z' } }));
  await page.route('**/api/verification/preview?*', route => { scans++; return route.fulfill({ contentType: 'application/json', body: JSON.stringify({ stageToken: 'local-test', targets: [{hllk:'test',date:'2026-09-01',valid:true}] }) }); });
  await page.goto(`http://127.0.0.1:${process.env.PORT || 4545}/`);
  await page.waitForFunction(() => document.querySelector('#calendarGrid button'));
  await page.locator('#workChoices').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#workChoices').isVisible(), true);
  assert.equal(await page.locator('#createLlkMode').isVisible(), true);
  assert.equal(scans, 0);
  const calendarState = await page.evaluate(() => {
    calendarMonth = new Date(2026, 8, 1);
    calendarEntries = { dates: new Set(['2026-09-14', '2026-09-16']), available: true, complete: true, pagesScanned: 2, fetchedAt: '2026-09-18T06:00:00Z' };
    renderCalendar();
    document.querySelector('#selectUnfilledDaysBtn').click();
    const dates = [...unfilledDates];
    const selected = [...document.querySelectorAll('[aria-pressed="true"][data-calendar-date]')].map(button => button.dataset.calendarDate);
    const count = Number(document.querySelector('#previewBtn').dataset.workdays);
    calendarEntries.error = 'Pembacaan gagal';
    renderCalendar();
    const failureVisible = !document.querySelector('#calendarEntriesStatus').closest('details') && document.querySelector('#calendarEntriesStatus').textContent.includes('Pembacaan gagal');
    const unfilledDisabled = document.querySelector('#selectUnfilledDaysBtn').disabled;
    return { dates, selected, count, failureVisible, unfilledDisabled };
  });
  assert.equal(calendarState.dates.includes('2026-09-14'), false);
  assert.equal(calendarState.dates.includes('2026-09-16'), false);
  assert.equal(calendarState.dates.includes('2026-09-15'), true);
  assert.deepEqual(calendarState.selected, calendarState.dates);
  assert.equal(calendarState.count, calendarState.dates.length);
  assert.equal(calendarState.failureVisible, true);
  assert.equal(calendarState.unfilledDisabled, true);
  for (const supervisor of [{ verified: true, source: 'directory' }, { verified: false, source: 'llk-api' }, { verified: true, source: 'llk-api' }]) {
    await page.evaluate(employee => selectEmployee(employee), { ...employee, supervisor: { ...employee.supervisor, ...supervisor } });
    assert.equal(await page.locator('#examinerStatus').evaluate(node => node.classList.contains('is-confirmed')), supervisor.verified && supervisor.source === 'llk-api');
  }
  const result = await page.evaluate(() => {
    updateCalendarSelection('2026-08-31', '2026-09-04');
    const calendarCount = Number(document.querySelector('#previewBtn').dataset.workdays);
    document.querySelector('[name="workflowMode"][value="verify"]').checked = true;
    setWizardStep(2);
    const verify = { createHidden: document.querySelector('#createLlkMode').hidden, reviewHidden: !document.querySelector('#reviewStep').classList.contains('is-active') };
    document.querySelector('[name="workflowMode"][value="create"]').checked = true;
    renderPreview(['2026-09-01', '2026-09-02'].map(date => ({ date, items: [{ start: '08:00', end: '16:30', description: 'Pemeriksaan UI lokal', type: 'Utama', result: 'Selesai' }] })));
    setWizardStep(3);
    const collapsed = document.querySelectorAll('.day-details:not([open])').length;
    document.querySelector('[data-toggle-edit="0"]').click();
    const field = document.querySelector('[data-field="description"]');
    field.value = 'Isian diperbarui';
    field.dispatchEvent(new Event('input', { bubbles: true }));
    const edited = currentPreview[0].items[0].description;
    const sendDisabled = document.querySelector('#submitBtn').disabled;
    const results = document.createElement('div');
    results.innerHTML = verificationList([{ date: '2026-09-01', success: true }, { date: '2026-09-02', success: false, error: 'net::ERR_ABORTED' }], 'result');
    return { calendarCount, verify, collapsed, edited, sendDisabled, uncertain: results.querySelector('.verification-item--uncertain') !== null, details: results.querySelectorAll('.error-details').length };
  });
  assert.equal(result.calendarCount, 5);
  assert.deepEqual(result.verify, { createHidden: true, reviewHidden: true });
  assert.equal(result.collapsed, 2);
  assert.equal(result.edited, 'Isian diperbarui');
  assert.equal(result.sendDisabled, true);
  assert.equal(result.uncertain, true);
  assert.equal(result.details, 1);
  assert.equal(await page.locator('#createLlkMode').isVisible(), false);
  await page.locator('#changeDatesBtn').click();
  assert.equal(await page.locator('#createLlkMode').isVisible(), true);
  assert.equal(await page.evaluate(() => currentPreview[0].items[0].description), 'Isian diperbarui');
  await page.evaluate(() => setWizardStep(3));
  await page.locator('[name="workflowMode"][value="verify"]').check();
  assert.equal(scans, 0);
  await page.locator('#refreshWizardVerificationBtn').click();
  await page.waitForFunction(() => !document.body.classList.contains('is-busy'));
  await page.locator('#wizardVerificationMessage').fill('Pesan tetap tersimpan');
  await page.locator('[name="workflowMode"][value="create"]').check();
  assert.equal(await page.locator('#reviewStep').isVisible(), true);
  assert.equal(await page.locator('[data-field="description"]').first().inputValue(), 'Isian diperbarui');
  await page.locator('[name="workflowMode"][value="verify"]').check();
  assert.equal(await page.locator('#wizardVerificationMessage').inputValue(), 'Pesan tetap tersimpan');
  assert.equal(scans, 1);
  assert.equal(await page.locator('#logBox').isVisible(), true);
  const logState = await page.evaluate(() => {
    log('Urutan awal', 'Berjalan'); log('Urutan akhir token=RAHASIA', 'Selesai');
    const box = document.querySelector('#logBox'), text = box.textContent;
    for (let i = 0; i < 60; i++) log(`Proses ${i}`);
    const following = box.scrollHeight - box.scrollTop - box.clientHeight < 24;
    box.scrollTop = 0; log('Tidak merebut posisi baca');
    return { ordered: text.indexOf('Urutan awal') < text.indexOf('Urutan akhir'), safe: !text.includes('RAHASIA'), following, retained: box.scrollTop === 0 };
  });
  assert.deepEqual(logState, { ordered: true, safe: true, following: true, retained: true });
  await page.route('**/api/employees/session-check/calendar-entries?refresh=1', route => route.fulfill({ status: 401, json: { error: 'Sesi browser berakhir.' } }));
  sessionEmployee = null;
  await page.locator('[name="workflowMode"][value="create"]').check();
  await page.locator('#changeDatesBtn').click();
  await page.locator('#refreshCalendarEntriesBtn').click();
  await page.locator('#quickSsoLoginBtn').waitFor({ state: 'visible' });
  await page.waitForFunction(() => !document.body.classList.contains('is-busy'));
  assert.equal(await page.locator('#workspace').isVisible(), false);
  assert.equal(await page.locator('#wizardVerificationMessage').inputValue(), '');
  assert.equal(await page.locator('#logBox').evaluate(node => node.textContent.includes('Urutan awal')), false);
  assert.equal(await page.evaluate(() => currentPreview), null);
  sessionEmployee = employee;
  await page.reload();
  await page.locator('#workChoices').waitFor({ state: 'visible' });
  page.on('dialog', dialog => dialog.accept());
  await page.locator('#endSessionBtn').click();
  await page.locator('#quickSsoLoginBtn').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#workspace').isVisible(), false);
  assert.equal(await page.locator('#quickSupervisorNip').inputValue(), '');
  await page.reload();
  await page.locator('#quickSsoLoginBtn').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#workChoices').isVisible(), false);
  await page.locator('#ssoPassword').fill('password-uji-lokal');
  await page.locator('#togglePasswordBtn').click();
  assert.equal(await page.locator('#ssoPassword').getAttribute('type'), 'text');
  assert.equal(await page.locator('#ssoPassword').inputValue(), 'password-uji-lokal');
  await page.locator('#togglePasswordBtn').click();
  assert.equal(await page.locator('#ssoPassword').getAttribute('type'), 'password');
  await page.locator('#togglePasswordBtn').click();
  await page.evaluate(() => document.querySelector('#employeeForm').reset());
  assert.equal(await page.locator('#ssoPassword').getAttribute('type'), 'password');
  assert.equal(await page.locator('#ssoPassword').inputValue(), '');
  console.log('PASS: workflow, cross-month calendar, preview editing, required confirmation, and failure details. No production submissions.');
} finally { await browser.close(); }
