import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';
import { browserLaunchOptions } from './browser.mjs';

const browser = await chromium.launch({ ...browserLaunchOptions(), headless: true });
try {
  const page = await browser.newPage();
  let sessionStatus = 200, authenticated = true, scans = 0;
  await page.route('**/session/status', route => route.fulfill({ status: sessionStatus, contentType: 'application/json', body: JSON.stringify({ authenticated }) }));
  await page.route('**/api/verification/preview?*', route => { scans++; return route.fulfill({ contentType: 'application/json', body: JSON.stringify({ targets: [] }) }); });
  await page.goto('http://127.0.0.1:4545/');
  await page.waitForFunction(() => document.querySelector('#calendarGrid button'));
  await page.locator('#workChoices').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#workChoices').isVisible(), true);
  assert.equal(await page.locator('#createLlkMode').isVisible(), false);
  assert.equal(scans, 0);
  authenticated = false;
  await page.evaluate(() => checkAccountSession());
  await page.evaluate(() => setWizardStep(2));
  assert.equal(await page.locator('#loginBtn').isVisible(), true);
  assert.equal(await page.locator('#workChoices').isVisible(), false);
  sessionStatus = 503;
  await page.evaluate(() => checkAccountSession());
  assert.equal(await page.locator('#retrySessionBtn').isVisible(), true);
  assert.equal(await page.locator('#loginBtn').isVisible(), false);
  sessionStatus = 200; authenticated = true;
  await page.locator('#retrySessionBtn').click();
  await page.locator('#workChoices').waitFor({ state: 'visible' });
  const result = await page.evaluate(() => {
    updateCalendarSelection('2026-08-31', '2026-09-04');
    const calendar = document.querySelector('#calendarSummary').textContent;
    document.querySelector('[name="workflowMode"][value="verify"]').checked = true;
    setWizardStep(2);
    const verify = { title: document.querySelector('#workTitle').textContent, reviewHidden: document.querySelector('#navReview').hidden };
    document.querySelector('[name="workflowMode"][value="create"]').checked = true;
    renderPreview(['2026-09-01', '2026-09-02'].map(date => ({ date, items: [{ start: '08:00', end: '16:30', description: 'Pemeriksaan UI lokal', type: 'Utama', result: 'Selesai' }] })));
    setWizardStep(3);
    const collapsed = document.querySelectorAll('.day-details:not([open])').length;
    document.querySelector('[data-toggle-edit="0"]').click();
    const field = document.querySelector('[data-field="description"]');
    field.value = 'Isian diperbarui';
    field.dispatchEvent(new Event('input', { bubbles: true }));
    const edited = currentPreview[0].items[0].description;
    const sendDisabled = document.querySelector('#submitBtn').disabled;
    const results = document.createElement('div');
    results.innerHTML = verificationList([{ date: '2026-09-01', success: true }, { date: '2026-09-02', success: false, error: 'net::ERR_ABORTED' }], 'result');
    return { calendar, verify, collapsed, edited, sendDisabled, firstResult: results.querySelector('strong').textContent, details: results.querySelectorAll('.error-details').length };
  });
  assert.match(result.calendar, /^5 hari kerja dipilih · 0 hari dilewati/);
  assert.deepEqual(result.verify, { title: 'Verifikasi LLK Anggota', reviewHidden: true });
  assert.equal(result.collapsed, 2);
  assert.equal(result.edited, 'Isian diperbarui');
  assert.equal(result.sendDisabled, true);
  assert.equal(result.firstResult, '2026-09-02');
  assert.equal(result.details, 1);
  await page.locator('#reviewStep [data-change-work]').click();
  await page.locator('[name="workflowMode"][value="verify"]').check();
  await page.waitForFunction(() => !document.body.classList.contains('is-busy'));
  await page.locator('#wizardVerificationMessage').fill('Pesan tetap tersimpan');
  await page.locator('#verifyLlkMode [data-change-work]').click();
  await page.locator('[name="workflowMode"][value="create"]').check();
  assert.equal(await page.locator('#reviewStep').isVisible(), true);
  assert.equal(await page.locator('[data-field="description"]').first().inputValue(), 'Isian diperbarui');
  await page.locator('#reviewStep [data-change-work]').click();
  await page.locator('[name="workflowMode"][value="verify"]').check();
  assert.equal(await page.locator('#wizardVerificationMessage').inputValue(), 'Pesan tetap tersimpan');
  assert.equal(scans, 1);
  page.once('dialog', dialog => dialog.dismiss());
  await page.evaluate(() => selectEmployee(employees.find(employee => employee.id !== active.id)));
  assert.equal(await page.locator('#wizardVerificationMessage').inputValue(), 'Pesan tetap tersimpan');
  page.once('dialog', dialog => dialog.accept());
  await page.evaluate(() => selectEmployee(employees.find(employee => employee.id !== active.id)));
  assert.equal(await page.locator('#wizardVerificationMessage').inputValue(), '');
  assert.equal(await page.locator('#startDate').inputValue(), '');
  assert.equal(await page.evaluate(() => currentPreview), null);
  console.log('PASS: workflow, cross-month calendar, preview editing, required confirmation, and failure details. No production submissions.');
} finally { await browser.close(); }
